apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-backend-deployment          # Deployment name
spec:
  replicas: 1                                # Number of backend pods
  selector:
    matchLabels:
      app: diabetes-backend                  # Selector matches pod template labels
  template:
    metadata:
      labels:
        app: diabetes-backend                # Labels applied to backend pods
    spec:
      containers:
        - name: backend
          image: gcr.io/finalprojml/backend:latest   # Backend image stored in GCR
          imagePullPolicy: IfNotPresent              # Avoid repeated pulls unless needed
          ports:
            - containerPort: 8000                    # Container exposes port 8000
          env:
            - name: MODEL_PATH                       # Environment variable for ML model path
              value: /app/models/diabetes_model.pkl
