apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-frontend-deployment       # Deployment name
spec:
  replicas: 1                               # One frontend pod
  selector:
    matchLabels:
      app: diabetes-frontend                # Must match template labels
  template:
    metadata:
      labels:
        app: diabetes-frontend              # Labels applied to frontend pods
    spec:
      containers:
        - name: frontend
          image: gcr.io/finalprojml/frontend:latest    # Frontend image in GCR
          imagePullPolicy: IfNotPresent                # Pull only if needed
          ports:
            - containerPort: 80                        # Frontend serves HTTP on port 80
