apiVersion: v1
kind: Service
metadata:
  name: diabetes-frontend-service
  labels:
    app: diabetes-frontend
spec:
  type: ClusterIP
  selector:
    app: diabetes-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
