apiVersion: v1
kind: Service
metadata:
  name: diabetes-frontend-service           # Service name
  labels:
    app: diabetes-frontend                  # Label on the Service
spec:
  type: ClusterIP                           # Internal cluster service
  selector:
    app: diabetes-frontend                  # Connects service â†’ frontend pods
  ports:
    - protocol: TCP
      port: 80                              # Service port
      targetPort: 80                        # Pod/container port
