apiVersion: v1
kind: Service
metadata:
  name: diabetes-api-service
  labels:
    app: diabetes-api
spec:
  type: ClusterIP
  selector:
    app: diabetes-api
  ports:
    - protocol: TCP
      port: 8000          # service port inside cluster
      targetPort: 8000    # container port