apiVersion: v1
kind: Service
metadata:
  name: diabetes-backend-service            # Service name
  labels:
    app: diabetes-backend                   # Label on the Service itself (organizational)
spec:
  type: ClusterIP                           # Internal-only service
  selector:
    app: diabetes-backend                   # Connects service â†’ backend pods
  ports:
    - protocol: TCP
      port: 8000                            # Service port users inside cluster hit
      targetPort: 8000                      # Container port exposed by backend
