apiVersion: v1
kind: Service
metadata:
  name: diabetes-api-service
  labels:
    app: diabetes-api
spec:
  type: NodePort          # good for local/minikube; in cloud you might use LoadBalancer
  selector:
    app: diabetes-api
  ports:
    - protocol: TCP
      port: 8000          # service port inside cluster
      targetPort: 8000    # container port
      nodePort: 30080     # node port on the host (for local access)